[package]
name = "bitcoin-node-handshake"
version = "0.1.0"
edition = "2021"
authors = ["BowTiedDeployer"]

[dependencies]
thiserror = "1.0.48"
log = "0.4.20"
tokio = { version = "1.32.0", features = ["full"] }
bitcoin = "0.30.1"
chrono = "0.4.29"
rand = "0.8.5"